### ISSUE TITLE
tag a release 

### ISSUE THREAD

**Issue by rsignell-usgs** [dbuscombe-usgs/PyHum#1]
Please tag a release so we can build a conda package with a version on binstar.org

**Comment by ddbuscombe** [comment]
v1.0.7 tagged

**Comment by rsignell-usgs** [comment]
@dbuscombe-usgs , awesome!  
I should have looked first on pypi before bugging you here.   I see you already _did_ release a version of the code.  But it's nice to have it here on github also, consistent with pypi version.
