### ISSUE TITLE
Error: Invalid mode or filename

### ISSUE THREAD

**Issue by LZarri** [dbuscombe-usgs/PyHum#10]
I am running into issues before PyHum gives me a map, see below error code:

![image](https://cloud.githubusercontent.com/assets/16599334/12185391/8d13b1f8-b54f-11e5-8834-92021d3f4d7a.png)

I am using Windows 7 and Python 2.7. Here is a text file of the python script I am running

[BuscombeFix.txt](https://github.com/dbuscombe-usgs/PyHum/files/81873/BuscombeFix.txt)

Thank you for your help!

**Comment by ddbuscombe** [comment]
I can't replicate this issue, which is a Windows-specific error, but I have included 2 workarounds in the offending portion of the script, which should fix the issue. Please uninstall and reinstall the github version, using:

```
pip uninstall PyHum
pip install git+https://github.com/dbuscombe-usgs/PyHum.git
```

Please verify the install by using:

```
python -c 'import PyHum;print(PyHum.__version__)'
```

which should print 1.3.5 to the screen. Let me know (by replying here on 'issues') if it fixes the problem?

I am working on a new 'release' version (with new/improved features) that will also get pushed to PyPI soon (so you can install directly via pip) - more details to follow

**Comment by LZarri** [comment]
I installed PyHum 1.3.5 but now am receiving a NameError: global name 'array' is not defined

![image](https://cloud.githubusercontent.com/assets/16599334/12187288/7b528452-b55f-11e5-9c6e-258268337317.png)

**Comment by ddbuscombe** [comment]
Oops. Simple fix - new version available. please try again now

**Comment by LZarri** [comment]
A new error-this time with PyHum.map, see below:

![image](https://cloud.githubusercontent.com/assets/16599334/12191210/c1f7378c-b586-11e5-9854-778c3da51bde.png)

Thank you,
Liam

**Comment by LZarri** [comment]
Here is the full output, which includes a few maps. Getting there!

![image](https://cloud.githubusercontent.com/assets/16599334/12191238/21c3b974-b587-11e5-93d8-bcd7c3d49a34.png)

![image](https://cloud.githubusercontent.com/assets/16599334/12191248/377dce44-b587-11e5-897c-e44decdcbb6f.png)

![image](https://cloud.githubusercontent.com/assets/16599334/12191253/40842ef2-b587-11e5-991c-f0526963e212.png)

![image](https://cloud.githubusercontent.com/assets/16599334/12191256/4a800f0c-b587-11e5-91a0-8f94371af84c.png)

**Comment by ddbuscombe** [comment]
Right - 'dogrid' is no longer a variable. Just remove it from the list of
input arguments

On Thu, Jan 7, 2016 at 10:40 PM, LZarri notifications@github.com wrote:

> Here is the full output, which includes a few maps. Getting there!
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/16599334/12191238/21c3b974-b587-11e5-93d8-bcd7c3d49a34.png
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/16599334/12191248/377dce44-b587-11e5-897c-e44decdcbb6f.png
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/16599334/12191253/40842ef2-b587-11e5-991c-f0526963e212.png
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/16599334/12191256/4a800f0c-b587-11e5-91a0-8f94371af84c.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dbuscombe-usgs/PyHum/issues/10#issuecomment-169902121
> .

## 

---

Daniel Buscombe, Ph.D. |   Research Geologist.
Grand Canyon Monitoring and Research Center,
United States Geological Survey,
Flagstaff, AZ 86001        |   +1 928 556 7216
http://about.me/danielbuscombe
CV: http://dbuscombe-usgs.github.io/vitae.html
Talks: https://speakerdeck.com/dbuscombe
Software: https://github.com/dbuscombe-usgs
Follow @Grain_Size on twitter for DGS software updates

---

**Comment by LZarri** [comment]
It works! Attached is the working script:

[BuscombeScriptClean.txt](https://github.com/dbuscombe-usgs/PyHum/files/83281/BuscombeScriptClean.txt)
