### ISSUE TITLE
rmshadows win default

### ISSUE THREAD

**Issue by debboutr** [dbuscombe-usgs/PyHum#13]
I'm looking in the rmshadows script in v. 1.3.7 and am seeing that the derfault for win size in the arguments is getting loaded with the value 31.  

def rmshadows(humfile, sonpath, win=31, shadowmask=0, doplot=1):
    '''
    Remove dark shadows in scans caused by shallows, shorelines, and attenuation of acoustics with distance
    Manual or automated processing options available
    Works on the radiometrically corrected outputs of the correct module

```
Syntax
----------
[] = PyHum.rmshadows(humfile, sonpath, win, shadowmask, doplot)

Parameters
----------
humfile : str
   path to the .DAT file
sonpath : str
   path where the *.SON files are
win : int, *optional* [Default=100]
   window size (pixels) for the automated shadow removal algorithm
```

Would a larger window size remove more shadows or a smaller window size?

Thanks

**Comment by ddbuscombe** [comment]
It depends on your data. The window size controls mostly the resolution with which data are analyzed for shadows. 31 pixels seems to work ok for most scans I've tested. It's a trial and error thing
