### ISSUE TITLE
pykdtree available only for Linux?

### ISSUE THREAD

**Issue by LZarri** [dbuscombe-usgs/PyHum#17]
Hi folks,

I get the notification "install pykdtree for faster kd-tree operations: https://github.com/storpipfugl/pykdtree" when running any PyHum script.

![image](https://cloud.githubusercontent.com/assets/16599334/13232085/7d6f0eb4-d962-11e5-9429-4d5f5abcadde.png)

When attempting to install this library using: 

python setup.py install (inside of pykdtree download folder)

I get the error message "TypeError: unsupported operand type(s) for %: 'tuple' and 'str'" 

![image](https://cloud.githubusercontent.com/assets/16599334/13232149/be610e0e-d962-11e5-8de8-84c659317d47.png)

When looking at the github site, it appears that this library may only be available for Linux. Is this the case?

**Comment by ddbuscombe** [comment]
It appears so:

https://github.com/storpipfugl/pykdtree/issues/2

I implemented pykdtree because (1) I am developing on Linux; and (2) it makes things a LOT (up to hundreds of times) faster
