### ISSUE TITLE
Specify output file and name to test outcome of different variables (resolution, mode)

### ISSUE THREAD

**Issue by LZarri** [dbuscombe-usgs/PyHum#20]
Hello,

I have been able to generate PyHum.map_texture maps of our humminbird sonar data, but the output is different from what I expected and somewhat indecipherable. 

![image](https://cloud.githubusercontent.com/assets/16599334/14090400/00389f84-f4ef-11e5-89ef-688ceee13345.png)

Is it possible to clean up the image using resolution or mode, or is what I am seeing the true distribution of sediment size across the river?

Finally, can I save the output name of my PyHum.map_texture file to test different variables of resolution, for example, against one another?

Thank you,
Liam

**Comment by ddbuscombe** [comment]
Yes the graphical display of the texture lengthscale data is not great. I'm trying to find time to work on it - unfortunately I don't have much time to work on it over the next couple of months. The map_texture module produces ascii point clouds of georeferenced texture lengthscales.  I suggest you create a map of the texture lengthscales either in an external program such as a GIS, or your own python script
