### ISSUE TITLE
Why does PyHum.map_texture give many raster ouputs?

### ISSUE THREAD

**Issue by LZarri** [dbuscombe-usgs/PyHum#21]
I get many outputs for: 
**sonpath+’class_GroundOverlay’+str(p)+’.kml’: kml file**
(contains gridded (or point cloud) texture lengthscale map for importing into google earth of the pth chunk)

which is the output I am most interested in. For example:

![image](https://cloud.githubusercontent.com/assets/16599334/14090562/fe5fdbc2-f4ef-11e5-8cc3-c395f270662c.png)

Why is this, and which is the best to use? Should I use all of them?

Thank you,
Liam

**Comment by ddbuscombe** [comment]
This is normal if you specified more than 1 chunk, e.d. with a 'd', or 'p' prefix. If you only want one chunk, use chunk = '1' argument in the read module
