### ISSUE TITLE
"Something went wrong with the parallelised version of pyread ... "

### ISSUE THREAD

**Issue by LZarri** [dbuscombe-usgs/PyHum#23]
Please help with my most recent issue,

I just collected some humminbird sonar data and am trying to process it. The following error message pops up:

![image](https://cloud.githubusercontent.com/assets/16599334/14547403/f7ca9d72-0261-11e6-9377-6f69b835c0cf.png)

I ran 'pip install PyHum --upgrade' to attempt to fix the issue, to no avail.

Attached is the .py file, .bat file to run the .py file.

Thank you!
Liam

**Comment by LZarri** [comment]
[working_2.zip](https://github.com/dbuscombe-usgs/PyHum/files/220150/working_2.zip)

**Comment by ddbuscombe** [comment]
Liam, try giving it model=998 instead (or model = 798)

**Comment by LZarri** [comment]
Model = 798 worked. Thank you!
