### ISSUE TITLE
Specifying 1 chunk throws a IO Error

### ISSUE THREAD

**Issue by LZarri** [dbuscombe-usgs/PyHum#27]
Hello all,

I have ran into a problem when attempting to display PyHum in just 1 chunk. 

![image](https://cloud.githubusercontent.com/assets/16599334/16641099/30203de4-43b2-11e6-8169-5afea1ed40cc.png)

This problem does not occur if I specify more than one chunk IE 'h5' or 'd100'. PyHum is also running very slowly when stating "27027 windows to process". I noticed that CPU usage goes to 100% when processing windows-do I need more CPU to avoid this error? 

Thanks,
Liam

**Comment by ddbuscombe** [comment]
I can't reproduce the error. Please provide the offending data file
