### ISSUE TITLE
proc_mysidescandata.py

### ISSUE THREAD

**Issue by debboutr** [dbuscombe-usgs/PyHum#29]
Just a head's up with the script that you have included in the page below,  the objects (f, chunk_size, calc_bearing, filt_bearing, and cog) all go undefined when I copy and paste the snippet that you want to call proc_mysidescandata.py into a script. 

[http://dbuscombe-usgs.github.io/PyHum/README.html#gettingstarted](url)

**Comment by ddbuscombe** [comment]
Thanks - I'll be changing the website soon with updated instructions. Things move too fast with the code development and I can't keep up!!
