### ISSUE TITLE
Output directory location fail

### ISSUE THREAD

**Issue by debboutr** [dbuscombe-usgs/PyHum#32]
Is there a way to identify a directory where you would like output to be placed?  I am working through these modules in this order, like is done in your test script,:

read()
correct()
rmshadows()
texture()
map()
map_texture()
e1e2()

 It is putting the created .dat / .mat files in the humfile directory, and the created png files in the sonfile directory, does this seem right? Anyway if you look at the traceback below there seems to be a problem with the handling of these paths.

`Traceback (most recent call last):
  File "C:\Users\Rdebbout\temp\SideScanSonar\processSideScan.py", line 60, in <m
odule>
    PyHum.texture(humfile, sonpath)
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda2\envs\sss\lib\site-pa
ckages\PyHum\_pyhum_texture.py", line 216, in texture
    ft = 1/loadmat(sonpath+base+'meta.mat')['pix_m']
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda2\envs\sss\lib\site-pa
ckages\scipy\io\matlab\mio.py", line 134, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda2\envs\sss\lib\site-pa
ckages\scipy\io\matlab\mio.py", line 57, in mat_reader_factory
    byte_stream = _open_file(file_name, appendmat)
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda2\envs\sss\lib\site-pa
ckages\scipy\io\matlab\mio.py", line 23, in _open_file
    return open(file_like, 'rb')
IOError: [Errno 22] invalid mode ('rb') or filename: 'C:/Users/Rdebbout/temp/Sid
eScanSonar/R00021\\C:/Users/Rdebbout/temp/SideScanSonar/R00021meta.mat'`

The meta.mat file has been created in the same directory where the humfile is located:

`humfile = 'C:/Users/Rdebbout/temp/SideScanSonar/R00021.DAT'

C:/Users/Rdebbout/temp/SideScanSonar/R00021meta.mat`

**Comment by ddbuscombe** [comment]
It is best if the .DAT (humfile) is within the sonpath directory
