### ISSUE TITLE
PyHum.gui() error

### ISSUE THREAD

**Issue by debboutr** [dbuscombe-usgs/PyHum#37]

**Comment by debboutr** [comment]
I was trying to use the gui and got the following error:

[PyHumGUIerror.txt](https://github.com/dbuscombe-usgs/PyHum/files/554627/PyHumGUIerror.txt)

I'm only guessing, but it seems that the popup window to select .SON files only lets you choose al of the son files in the directory not just the directory itself

**Comment by ddbuscombe** [comment]
Fixed in version 1.3.15
