### ISSUE TITLE
mosaic_texture NameError -- 'noisefloor'

### ISSUE THREAD

**Issue by debboutr** [dbuscombe-usgs/PyHum#39]
Using 1.3.14 I'm getting the following error when running through the mosaic_texture module.

`Input file is C:\Users\Rdebbout\SideScanTEST\R00023.DAT
Sonar file path is C:\Users\Rdebbout\SideScanTEST\R00023
cs2cs arguments are epsg:26991
Gridding resolution: 99.0
Number of nearest neighbours for gridding: 5
Weighting for gridding: 1
creating grids ...
mosaicking ...
Traceback (most recent call last):
  File "C:\Users\Rdebbout\SideScanTEST\processSideScan.py", line 67, in <module>

    PyHum.mosaic_texture(humfile, sonpath, cs2cs_args)
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda2\envs\sidescan3\lib\s
ite-packages\PyHum\_pyhum_mosaic_texture.py", line 357, in mosaic_texture
    S[S<noisefloor] = np.nan
NameError: global name 'noisefloor' is not defined`

**Comment by ddbuscombe** [comment]
Fixed in 1.3.17. Please note that the mosaic module is alpha (untested) so feel free to contribute towards its development
