### ISSUE TITLE
Run time

### ISSUE THREAD

**Issue by luojing1211** [dbuscombe-usgs/PyHum#5]
Hi PyHum developers, 

I have a quick question about the run time. When I do the test, it take me more then a half day but the test is still not finished. Is it because that my computer is too slow? And what is the recommended computer?

My computer is  1.3 Ghz inter Core i5 and 4GB 1600MHz DDR3 Mac.

**Comment by ddbuscombe** [comment]
It should run in just a few minutes. Please could you tell me which Python version and OS you are running? Also, which function does it bog down on? A screengrab would be helpful, thanks!

**Comment by luojing1211** [comment]
I am using python 2.7 and OSX 10.9.5  And here are the screens

![screen shot 2015-07-21 at 10 33 25 pm](https://cloud.githubusercontent.com/assets/5324931/8817440/f096dcc8-2ff8-11e5-9ffe-a502346ff551.png)
![screen shot 2015-07-21 at 10 35 03 pm](https://cloud.githubusercontent.com/assets/5324931/8817439/f0968070-2ff8-11e5-989c-c7e758010371.png)
Thanks a lot.

**Comment by ddbuscombe** [comment]
It looks as though it is stuck in an infinite loop in the parallel processing. what is your joblib library version?

import joblib
joblib.**version**

**Comment by ddbuscombe** [comment]
"joblib.**version**"

**Comment by luojing1211** [comment]
Here is the version
import joblib
"joblib.**version**"
'0.8.4'

**Comment by ddbuscombe** [comment]
It might be related to issues discussed here:
https://github.com/joblib/joblib/issues/138

Could you try adding this to the top of the test.py script and see if it makes any difference?

import os
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['OMP_NUM_THREADS'] = '1'
os.environ['MKL_DYNAMIC'] = 'FALSE'

**Comment by luojing1211** [comment]
I have tried it. But it still takes a very long time.

**Comment by ddbuscombe** [comment]
Does it complete all programs without error? If so, how much time does it take?

**Comment by luojing1211** [comment]
It is just keeping like: 
![screen shot 2015-07-22 at 9 46 02 pm](https://cloud.githubusercontent.com/assets/5324931/8842065/2d082e1a-30bb-11e5-8722-0fa841164c80.png)

**Comment by ddbuscombe** [comment]
It should take a minute or less for the first program (read) to complete in the test script. I would guess it's an error associated with the joblib (parallel processing libraries), but I'm not sure what the specific issue is. Please try using an older version of joblib, e.g.:

```
pip uninstall joblib
pip install joblib==0.7.1
```

**Comment by danhamill** [comment]
When the program appears to crash, what does your activity monitor say is happening?  Is Python listed as a process using your CPU time?

**Comment by luojing1211** [comment]
I fixed it. I reinstall the package for github instead of the pip package. It seems to work. I am using joblib version 0.7.1
