### ISSUE TITLE
DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by ryanhefley** [dbuscombe-usgs/PyHum#53]
Hello again,
Was trying to install this package on one of the engineers computer who sent me on figuring out this package to begin with. We went through your latest install anaconda prompt commands and had no issues whatsoever! *HOORAY* :) 
However, when we went to do the `python -c"import PyHum; PyHum.dotest()"` we ran into a import gui error and a DLL load failed error

![image](https://user-images.githubusercontent.com/7328971/35528125-8238fc12-04f2-11e8-8339-8a1d84a3b75e.png)

Any ideas on what could have caused this?

**Comment by ddbuscombe** [comment]
Update your Pillow install

```
pip install -U pillow
```

**Comment by ryanhefley** [comment]
@dbuscombe-usgs I told him what to do, and when he did `pip install -U pillow` it said "Requirement already up-to-date"
![image](https://user-images.githubusercontent.com/7328971/35532218-19aa5d1e-04ff-11e8-86d2-91e0fa0947a0.png)

**Comment by ddbuscombe** [comment]
```
pip install pillow --upgrade
```

?

**Comment by danhamill** [comment]
I had the same problem on my machine.  I found a workaround was to
uninstall and re-install pillow.

```
pip uninstall pillow
pip install pillow

```

**Comment by ryanhefley** [comment]
@danhamill @dbuscombe-usgs  thank you guys so much for your fast response times and helpfulness! Love this library. 
By uninstalling and reinstalling pillow, Rusty was able to get the PyHum.dotest() to work and we were also able to use the script for him to use his own data!
