### ISSUE TITLE
_pyhum_texture2.py error

### ISSUE THREAD

**Issue by cambodine** [dbuscombe-usgs/PyHum#54]
Hey guys, 
Found an issue with _pyhum_texture2.py on line 324:

Change:
`plot_contours(dist_m, shape_port, class_fp[p], ft, humfile, sonpath, base, numclasses, p)`

to:
`plot_contours(dist_m, shape_port, port_fp[p], star_fp[p], class_fp[p], ft, humfile, sonpath, base, numclasses, p)`

At least that solved the issue of plotting contours for me.

Thanks!

**Comment by ddbuscombe** [comment]
Thanks - I will incorporate in the next release
