### ISSUE TITLE
Installation problems in conda environment

### ISSUE THREAD

**Issue by jasonfischer** [dbuscombe-usgs/PyHum#56]
First off, thanks for all of the work on the PyHum package! I am looking forward to using PyHum on some of my sonar data, but have been have trouble importing PyHum after installing it in a conda virtual environment. Following the steps on the github page, I am able to successfully install PyHum-1.4.6, but cannot load and test the package. After entering the command

> python -c ”import PyHum;PyHum.dotest()”

I receive the following error message “ImportError: DLL load failed: The specified module could not be found”. Based on the output below, I assume this pertains to the PIL library, but I am not sure how to resolve the issue. I am new to python, so my apologies if I am missing something basic. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/9321864/36644045-779dd6f2-1a22-11e8-8822-a5a461061099.png)

Other background information: I am using a pc running the Windows 10 operating system and the 64-bit version of miniconda.

Thanks,
Jason

**Comment by danhamill** [comment]
Hi jason,

Try uninstalling and reinstalling pillow. 

pip uninstall pillow 
pip install pillow

Dan

**Comment by jasonfischer** [comment]
Thanks Dan,

Reinstalling pillow did the trick. I do get a "plot could not be produced" message at the end of the test, but that sounds like a known issue (#49).

-Jason
