### ISSUE TITLE
PyHum_map output

### ISSUE THREAD

**Issue by jasonfischer** [dbuscombe-usgs/PyHum#57]
This isn't an issue per se, but what attributes does pyhum_map export in the point cloud text file? The help file states that easting, northing, and sidescan intensity are returned, but the text file I receive has seven columns with no headers. The first two columns look like spatial coordinates, but what are the other four attributes?

**Comment by ddbuscombe** [comment]
The columns are: 
X (projected coordinate according to specified cs2cs_args)
Y (projected coordinate according to specified cs2cs_args)
sidescan intensity (dB W)
range to sonar (m)
depth (m, flat bottom assumption)
heading (relative to N)

**Comment by ddbuscombe** [comment]
heading in in radians
